In [1]:
import cv2
import numpy as np

In [2]:
def readImg():
    image = cv2.imread("./image/20200526.png")
    return image

def showImg(image):
    cv2.imshow("shinchon20200526", image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
img = readImg()
showImg(img)

In [3]:
(height, width) = img.shape[:2]
center = (width // 2, height // 2)

In [6]:
# 원ㅂ논 이미지와 가로 세로 비율이 똑같고, 모두 0으로 채워진 배열(이미지) 생성
mask = np.zeros(img.shape[:2], dtype="uint8")
print(mask.shape)
print(mask)
showImg(mask)

(600, 600)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
# 중점 좌표 center, 반지름 300짜리 원을 흰색으로 채워서 mask 이미지에 그림
cv2.circle(mask, center, 300, (255,255,255), -1)
print(mask)
showImg(mask)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
# img와 mask 이미지를 mask 방식으로 합칩니다(and 연산 : 둘 다 True면 1, 아닌 나머지는 0)
# mask 이미지의 원은 모두 1, 나머지는 0이므로 원의 내부에서 합쳐지는 img 이미지가 표시되고, 이미
# 모두 0인 mask의 원 외부영역은 img 이미지에 무엇이 있든 모두 0으로 계산됨
masked = cv2.bitwise_and(img, img, mask=mask)
# () = 앞 img = img + mask 를 의미
showImg(masked)

In [ ]:
# 11111111 and 10100011  ->  10100011
# 0과 and 연산된 A -> 0
# 1과 and 연산된 A -> A