In [1]:
import cv2
import numpy as np
min_confidence = 0.5

In [2]:
# 모델 로딩
net = cv2.dnn.readNet("yolo/yolov3.weights", "yolo/yolov3.cfg")

In [3]:
# 화면에 표시될 사물의 이름들을 기록한 파일을 열어서 로딩, 저장해둡니다
with open("yolo/coco.names", "r")as f:
    classes = [line.strip() for line in f.readlines()]
    print(classes)

['person', 'bicycle', 'car', 'motorbike', 'aeroplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'sofa', 'pottedplant', 'bed', 'diningtable', 'toilet', 'tvmonitor', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']


In [4]:
# 랜덤의 색상 결정
colors = np.random.uniform(0, 255, size=(len(classes), 3))
print(colors)

[[5.08232282e+01 1.07748641e+02 2.89673038e+01]
 [5.37304956e+01 9.97087313e+01 2.05644232e+02]
 [1.49335847e+02 2.25002570e+02 2.21486841e+02]
 [1.74147084e+02 9.02361475e+01 2.37123144e+01]
 [1.21375860e+02 1.60732222e+02 1.92820705e+02]
 [7.84876895e+01 1.50098977e+02 6.79513694e+00]
 [1.47684200e+02 1.35195098e+02 6.65227455e+01]
 [1.95008437e+02 1.70649810e+02 6.08865501e+00]
 [1.19269531e+02 8.18881579e+01 6.29186261e+01]
 [2.30526549e+02 1.48635632e+01 2.15440032e+02]
 [2.18913014e+02 2.95490091e+01 2.34469390e+02]
 [8.99502321e+01 6.68294781e+01 1.12072057e+02]
 [1.56166665e+02 2.16631697e+02 5.96575107e+01]
 [2.24456396e+02 1.47740930e+02 2.02301611e+02]
 [5.04043499e+01 4.29524312e+01 8.27246476e+01]
 [1.90974340e+02 9.08646735e+01 1.42913834e+02]
 [1.44342509e+01 4.37801354e+01 1.95941680e+02]
 [1.78330469e+02 2.06432444e+02 5.18498743e+00]
 [1.71809421e+02 3.54308950e+01 1.63197951e+01]
 [1.86334809e+02 3.50975799e+00 1.17715837e+01]
 [1.67127835e+02 7.75607789e+01 4.866692

In [5]:
# net 변수에 로딩된 모델에서, 출력양식(인식된 사물의 추가정보) 설정 내용을 추출합니다
layer_names = net.getLayerNames()
output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]

In [6]:
# 이미지 로딩 & 크기 추출
img = cv2.imread("image/shinchon_copy.jpg")
height, width, channels = img.shape

In [7]:
# 이미지 형식 변환
blob = cv2.dnn.blobFromImage(img, 0.00392, (416, 416), (0,0,0), True, crop=False)
# 모델에 이미지 set
net.setInput(blob)
# 이미지 내부에 있는 사물 인식 실행
outs = net.forward(output_layers)
# 표시할 사물의 사각형 및 확률 등을 저장할 리스트 생성
class_ids = []
confidences = []
boxes = []

In [8]:
print(outs[0].shape)

(507, 85)


In [9]:
# 인식된 사물의 개수만큼 반복실행
for out in outs:
    # 인식된 사물의 판별 정보별로 반복실행
    for detection in out:
        # 인식 가능한 사물일 가능성이 담긴 확률들을 먼저 추출
        scores = detection[5:]
        # 확률들을 정렬하고 가장 높은 확률의 인덱스 추출
        class_id = np.argmax(scores)
        # 해당 인덱스의 확률 추출
        confidence = scores[class_id]
        # 추출한 확률이 50%(0.5 이상인 경우)
        if confidence > min_confidence:
            # 해당 사물의 중점 좌표 계산
            center_x = int(detection[0] * width)
            center_y = int(detection[1] * height)
            # 가로 세로 길이 및 시작 좌표 계산
            w = int(detection[2] * width)
            h = int(detection[3] * height)
            x = int(center_x - w / 2)
            y = int(center_y - h / 2)
            # 계산된 좌표 정보 및 확률 그리고 사물이름(class_id) 정보를 각 리스트에 저장합니다
            boxes.append([x, y, w, h])
            confidences.append(float(confidence))
            class_ids.append(class_id)

In [10]:
class_ids

[0, 0, 0, 0, 0, 0, 0, 0, 0]

In [11]:
# 작성할 텍스트의 포트 설정
font = cv2.FONT_HERSHEY_PLAIN

# 인식된 사물에 대한 노이즈 제거작업(중복박스 제거)
indexes = cv2.dnn.NMSBoxes(boxes, confidences, min_confidence, 0.4)
# boxes : 사각형 정보들
# confidences : 모든 박스들의 확률값
# min_confidence : 1차 임계값
# 0.4 : 동일 박스들에서 실제 사물에 해당되는 것을 제외한 나머지를 제거할 2차 임계값
#       (표시할 box의 내용이 담긴 인덱스만 추출)

for i in range(len(boxes)):
    if i in indexes:
        x, y, w, h = boxes[i]
        label = str(classes[class_ids[i]])
        print(i, label)
        color = colors[i]
        cv2.rectangle(img, (x, y), (x+w, y+h), color, 2)
        cv2.putText(img, label, (x, y+30), font, 2, (0, 255, 0), 1)
cv2.imshow("YOLO Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

2 person
4 person
7 person
