### Numpy ndarray
* 판다스가 데이터프레임을 기반으로 한 데이터 가공과 분석에 관한 모듈이라면, 넘파이는 수학적 연산 및 처리 도구들을 제공하는 모듈입니다
* 판다스와 넘파이 둘은 데이터 분석과 머신러닝 분야에서 없어서는 안되는 중요 모듈로 사용되고 있습니다

### ndarray 생성, np.array()

In [66]:
import numpy as np

In [67]:
# 일반적 리스트의 사용, 데이터형 출력
list1 = [1,2,3]
print("list1", list1)
print("list1 type", type(list1))

list1 [1, 2, 3]
list1 type <class 'list'>


In [68]:
# 사용하던 리스트 데이터를 ndarray로 쉽게 변형하여 사용이 가능합니다
array1 = np.array(list1)
print("array1:", array1)
print("array1 type:", type(array1))

array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


* ndarray의 형태(shape)와 차원

In [69]:
# 1차원 배열
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)
# shape : 행의 개수와 열의 개수를 표현해주는 ndarray 속성입니다.
# 현재는 1차원 배열을 사용하고 있으므로 열의 개수는 공란으로 표현됩니다

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [70]:
# 2차원 리스트와 형태가 비슷한 2차원 ndarray
array2 = np.array([[1,2,3],[2,3,4]])
print(array2)
print('array2 type', type(array2))
print('array2 array 형태:', array2.shape)

[[1 2 3]
 [2 3 4]]
array2 type <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [71]:
array3 = np.array([[1,2,3]])
print(array3)
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

[[1 2 3]]
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [72]:
array3_ = np.array([[1],[2],[3]])
print(array3_)
print('array3_ type:', type(array3_))
print('array3_ array 형태:', array3_.shape)

[[1]
 [2]
 [3]]
array3_ type: <class 'numpy.ndarray'>
array3_ array 형태: (3, 1)


In [73]:
array4 = np.array([[1,2],[3,4],[5,6]])
print(array4)

[[1 2]
 [3 4]
 [5 6]]


In [74]:
# .ndim : ndarray의 차원구성(shape 차수값)을 저장하고 있는 속성
print('array1:{0}차원, array2:{1}차원, array3:{2}차원'.format(\
                                                       array1.ndim, array2.ndim, array3.ndim))

array1:1차원, array2:2차원, array3:2차원


In [75]:
# 3차원 ndarray : 아래 배열은 2행 2열짜리 배열이 3개 있는 모양
array0 = np.array([ [[1,2],[3,4]], [[5,6],[7,8]], [[9,10],[11,12]] ])
print("차원값 : ", array0.ndim)
print("모양 : ", array0.shape)
print(array0)

차원값 :  3
모양 :  (3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [76]:
list2 = [1,2,'test']
array2 = np.array(list2)
print('배열의 값', array2, '  배열의 데이터 타입',array2.dtype)
# .dtype이 갖는 값은 ndarray 구성에 따라 달라집니다
# 정수형 + 문자형 : <U11
# 정수형 + 실수형 + 문자형 : <U32
# 문자형 : <U2

배열의 값 ['1' '2' 'test']   배열의 데이터 타입 <U11


In [77]:
# 정수형 + 실수형 : float64
# 정수와 실수가 array에 섞이면 모든 데이터가 실수로 변환
list3 = [1,2,3.0]
array3 = np.array(list3)
print('배열의 값', array3, '  배열의 데이터 타입',array3.dtype)

배열의 값 [1. 2. 3.]   배열의 데이터 타입 float64


### astype()을 통한 타입변환

In [78]:
# 정수 -> 실수
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print('배열의 값',array_float,'  배열의 데이터 터입',array_float.dtype)

배열의 값 [1. 2. 3.]   배열의 데이터 터입 float64


In [79]:
# 실수 -> 정수
array_float1 = np.array([1.1,2.1,3.9])
array_int2 = array_float1.astype('int32')
print('배열의 값',array_int2,'  배열의 데이터 터입',array_int2.dtype)

# 정수 -> 문자
array_str1 = array_int2.astype('str')
print('정수 -> 문자 : ', array_str1, array_str1.dtype)

# 실수 -> 문자
array_str2 = array_float1.astype('str')
print('실수 -> 문자 : ', array_str2, array_str2.dtype)

# 문자 -> 정수
array_int3 = array_str1.astype('int32')
print('문자 -> 정수 : ', array_int3, array_int3.dtype)

# 문자 -> 실수
array_float3 = array_str2.astype('float64')
print('문자 -> 실수 : ', array_float3, array_float3.dtype)

# U11, U32 : 유니코드로 사용되는 문자열 자료형

배열의 값 [1 2 3]   배열의 데이터 터입 int32
정수 -> 문자 :  ['1' '2' '3'] <U11
실수 -> 문자 :  ['1.1' '2.1' '3.9'] <U32
문자 -> 정수 :  [1 2 3] int32
문자 -> 실수 :  [1.1 2.1 3.9] float64


### ndarray에서 axis 기반의 연산함수 수행

In [80]:
# axis=0은 행단위의 작업 (알고 있는 것과는 달리 세로 연산)
# axis=1은 열단위의 작업 (알고 있는 것과는 달리 가로 연산)
array2 = np.array([[1,2,3],[2,3,4]])
print(array2)
print(array2.sum())
print(array2.sum(axis=0))  # 같은 열의 데이터 합계(결과 : 세개의 값)
print(array2.sum(axis=1))  # 같은 행의 데이터 합계(결과 : 두개의 값)

[[1 2 3]
 [2 3 4]]
15
[3 5 7]
[6 9]


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [81]:
# 우리가 알고있는 range 함수와 거의 비슷한 arange를 이용한 숫자 발생으로 ndarray 생성

# 아래는 0~10 사이에 있는 짝수발생(10제외)
sequence_array = np.arange(0,10,2)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 2 4 6 8]
int32 (5,)


In [82]:
# zeros : 0들,  ones : 1들
# zeros(3,2) : 3행 2열짜리 0들을 발생
# ones(3,2) : 3행 열짜리 1들을 발생

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.zeros((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64 (3, 2)


### ndarray의 shape를 변경하는 reshape()

In [83]:
array1 = np.arange(10)
print('array1:\n', array1)

# 배열의 요소 개수가 유효하게 분재될 수 있는 구조로 행렬을 조절할 수 있다
array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [84]:
# 변환할 수 없는 shape 구조를 입력하면 오류 발생
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

### reshape()에 -1 인자값을 부여하여 특정차원으로 고정된 가변적인 ndarrya형태 변환

In [86]:
array1 = np.arange(10)
print(array1)

# 열의 크기는 5에 고정하고 행의 크기를 이에 맞춰 자동으로 변환, 즉 2X5 형태로 변환
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
print('array2:\n', array2)

# 로우 axis 크기는 5로 고정하고 컬럼 axis 크기는 이에 맞춰 자동으로 변환
# 즉 5X2 형태로 변환
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)
print('array3:\n',array3)

#reshape의 행렬중 한쪽이 변수의 값에 의존해서 결정이 될 때 사용
n=20
array1 = np.arange(100)
array4 = array1.reshape(n,-1)
print('array4 shape:', array4.shape)
print('array4:\n',array4)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array4 shape: (20, 5)
array4:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


In [87]:
# reshape()는 (-1,1), (-1,) 과 같은 형태로 주로 사용됨
# 1차원 ndarray를 2차원으로 또는 2차원 ndarray를 1차원으로 변환 시 사용
array1 = np.arange(5)
# 1차원 ndarray를 2차원으로 변환하되, 열의 크기는 반드시 1이여야 함
array2d_1 = array1.reshape(-1,1)
print("array2d_1 shape:", array2d_1.shape)
print("array2d_1:\n", array2d_1)

# (-1, ) : 2차원 ndarray를 1차원으로 변환
array1d = array2d_1.reshape(-1, )
print("array1d shape:", array1d.shape)
print("array1d:\n", array1d)

array2d_1 shape: (5, 1)
array2d_1:
 [[0]
 [1]
 [2]
 [3]
 [4]]
array1d shape: (5,)
array1d:
 [0 1 2 3 4]


In [88]:
# -1을 적용해도 변환이 불가능한 형태로의 변환을 요구할 경우 오류 발생
array1 = np.arange(10)
array4 = array1.reshape(-1,4)  # 에러
# 반드시 -1값은 1개의 인자만 입력해야 함
array1.reshape(-1,-1)  # 에러

ValueError: cannot reshape array of size 10 into shape (4)

### ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)
* 특정 위치의 단일값 추출

In [89]:
# 1에서부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:',array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))
print("맨 뒤의 값:", array1[-1], '  맨 뒤에서 두 번째 값 :', array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤의 값: 9   맨 뒤에서 두 번째 값 : 8


In [90]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
print('(row=0,col=0) index가 가리키는 값:', array2d[0,0])
print('(row=0,col=1) index가 가리키는 값:', array2d[0,1])
print('(row=1,col=0) index가 가리키는 값:', array2d[1,0])
print('(row=2,col=2) index가 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index가 가리키는 값: 1
(row=0,col=1) index가 가리키는 값: 2
(row=1,col=0) index가 가리키는 값: 4
(row=2,col=2) index가 가리키는 값: 9


### 슬라이싱

In [91]:
array1 = np.arange(start=1, stop=10)
print(array1)
array3 = array1[0:3]
print(array3)
print(type(array3))
array4 = array1[:3]
print(array4)
array5 = array1[3:]
print(array5)
array6 = array1[:]
print(array6)


[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [92]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2]:', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]:', array2d[1:3, 0:3])
print('array2d[1:3, :]:', array2d[1:3, :])
print('array2d[:, :]:', array2d[:, :])
print('array2d[:2, 1:]:', array2d[:2, 1:])
print('array2d[:2, 0]:', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]: [[1 2]
 [4 5]]
array2d[1:3, 0:3]: [[4 5 6]
 [7 8 9]]
array2d[1:3, :]: [[4 5 6]
 [7 8 9]]
array2d[:, :]: [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]: [[2 3]
 [5 6]]
array2d[:2, 0]: [1 4]


In [93]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1], 2]
print('array3', array3)
print('array2d[[0,1], 2] => ', array3.tolist())

array4 = array2d[[0,2], 0:2]
print('array4\n', array4)
print('array2d[[0,2], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]  # array5 = array2d[[0,1], :]
print('array5\n', array5)
print('array2d[[0,1]] => ', array5.tolist())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
array3 [3 6]
array2d[[0,1], 2] =>  [3, 6]
array4
 [[1 2]
 [7 8]]
array2d[[0,2], 0:2] =>  [[1, 2], [7, 8]]
array5
 [[1 2 3]
 [4 5 6]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱(Boolean indexing)

In [94]:
array1d = np.arange(start=1, stop=10)
print(array1d)
print(array1d>5)

# 연산의 결과를 array로
var1 = array1d > 5
print("var1:", var1)
print(type(var1))
print(var1.dtype)
# [ ]안에 array1d > 5의 결과를 얻어 Boolean indexing으로 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
var1: [False False False False False  True  True  True  True]
<class 'numpy.ndarray'>
bool
array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


### ndarray 값들을 이용한 인덱싱

In [95]:
print(array1d)
# 필터링(인덱싱)할 인덱스들을 리스트로 모아서 적용
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :', array4)

# 필터링할 값들을 리스트로 저장하고 적용
target = [6,7,8,9]
array_selected = np.array(target)
print('리스트로 값들을 생성한 결과 :', array_selected)

[1 2 3 4 5 6 7 8 9]
일반 인덱스로 필터링 결과 : [6 7 8 9]
리스트로 값들을 생성한 결과 : [6 7 8 9]


### 배열의 정렬 -sort()와 argsort()

In [96]:
org_array = np.array([3,1,9,5])  # 사본을 정렬, 수정
print("원본 행렬 :", org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬 :', sort_array1)
print('np.sort() 호출 후 원본 행렬 :', org_array)

원본 행렬 : [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 : [1 3 5 9]
np.sort() 호출 후 원본 행렬 : [3 1 9 5]


In [97]:
# ndarray.sort()로 정렬  (원본을 정렬, 수정)
sort_array2 = org_array.sort()
org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬 :', sort_array2)
print('org_array.sort() 호출 후 원본 행렬 :', org_array)

org_array.sort() 호출 후 반환된 행렬 : None
org_array.sort() 호출 후 원본 행렬 : [1 3 5 9]


In [98]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정룔 : ', sort_array1_desc)

내림차순으로 정룔 :  [9 5 3 1]


In [99]:
# 2차원 배열의 정렬
array2d = np.array([[8,12],[9,1]])
print("원본 : \n", array2d)
sort_array2d_axis0 = np.sort(array2d, axis=0)
print("row 방향으로 정렬 : \n", sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print("column 단으로 정렬 : \n", sort_array2d_axis1)

원본 : 
 [[ 8 12]
 [ 9  1]]
row 방향으로 정렬 : 
 [[ 8  1]
 [ 9 12]]
column 단으로 정렬 : 
 [[ 8 12]
 [ 1  9]]


In [100]:
# 3차원 배열의 정렬
array3d = np.array([ [[8,7],[3,1]], [[9,6],[7,5]], [[7,3],[11,12]] ])
print(array3d)
sort_array3d_axis0 = np.sort(array3d, axis=0)
print('axis=0으로 정렬:\n', sort_array3d_axis0)

sort_array3d_axis1 = np.sort(array3d, axis=1)
print('axis=1로 정렬:\n', sort_array3d_axis1)

sort_array3d_axis2 = np.sort(array3d, axis=2)
print('axis=2로 정렬:\n', sort_array3d_axis2)

[[[ 8  7]
  [ 3  1]]

 [[ 9  6]
  [ 7  5]]

 [[ 7  3]
  [11 12]]]
axis=0으로 정렬:
 [[[ 7  3]
  [ 3  1]]

 [[ 8  6]
  [ 7  5]]

 [[ 9  7]
  [11 12]]]
axis=1로 정렬:
 [[[ 3  1]
  [ 8  7]]

 [[ 7  5]
  [ 9  6]]

 [[ 7  3]
  [11 12]]]
axis=2로 정렬:
 [[[ 7  8]
  [ 1  3]]

 [[ 6  9]
  [ 5  7]]

 [[ 3  7]
  [11 12]]]


### argsort()

In [101]:
org_array = np.array([3,1,9,5])
print('일반 sort 결과 :', np.sort(org_array))

sort_index = np.argsort(org_array)  # argsort 실행
print('argsort 결과의 데이터 타입:',type(sort_index))  # 결과 데이터 타입
print('argsort의 결과 :', sort_index)  # 결과 배열 출력
# 원래있던 위치가 정렬되기 전의 인덱스 수치가 argsort로 출력
print('argsort의 결과중 가장 마지막 값을 원본 배열의 인덱싱값으로 사용(가장 큰 값)',\
      org_array[sort_index[-1]])

일반 sort 결과 : [1 3 5 9]
argsort 결과의 데이터 타입: <class 'numpy.ndarray'>
argsort의 결과 : [1 0 3 2]
argsort의 결과중 가장 마지막 값을 원본 배열의 인덱싱값으로 사용(가장 큰 값) 9


In [102]:
org_array = np.array([3,1,9,5])
print('일반 sort결과 :',np.sort(org_array)[::-1])
sort_index_desc = np.argsort(org_array)[::-1]
print('argsort 결과로 원본배열 인덱싱 :', org_array[sort_index_desc])

일반 sort결과 : [9 5 3 1]
argsort 결과로 원본배열 인덱싱 : [9 5 3 1]


In [103]:
name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([98,95,84,98,88])
# score_array의 정렬된 값에 해당하는 원본 행렬 위치 인덱스를 반환하고
# 이를 이용하여 name_array에서 name값 추출
sort_index = np.argsort(score_array)
print("sort index :", sort_index)
print("최고점자의 이름 :", name_array[sort_index[0]])

# 정렬결과 전체
name_array_sort = name_array[sort_index]
score_array_sort = score_array[sort_index]
print(name_array_sort)
print(score_array_sort)

sort index : [2 4 1 0 3]
최고점자의 이름 : Sarah
['Sarah' 'Samuel' 'Mike' 'John' 'Kate']
[84 88 95 98 98]
